### ISSUE TITLE
Link on farmOS.org

### ISSUE THREAD

**Issue by mstenta** [rkioski/farm_map_fi#1]
Hi @rkioski ! Thanks for creating this module!

Would you like me to add a link to it on farmOS.org?

It would appear under "Other modules" on this page: http://farmos.org/development/projects/

I would be happy to add your name/organization to the list of farmOS supporters too, if you'd like: http://farmos.org/community/supporters/

**Comment by rkioski** [comment]
Sure, why not

**Comment by mstenta** [comment]
Thanks - I added it to the list of projects.  If you'd like me to add you to the list of Supporters I just need to know what name to add.

Thanks again for the contribution!
